
all: p6_2

cpp14:
	g++ -std=c++14 -Wall -Werror -I/home/atul/cpp_practice_github main.cpp -o cpp14.out

p6_1:
	g++ -std=c++14 -Wall -Werror -I/home/atul/cpp_practice_github 6.1_dutch_natianal_flag.cpp -o 6_1.out

p6_2:
	g++ -std=c++14 -Wall -Werror -I/home/atul/cpp_practice_github 6.2_plus_one_array.cpp -o 6_2.out

