
all: p6_8

clean:
	rm -f *.out

cpp14:
	g++ -std=c++14 -Wall -Werror -I/home/atul/cpp_practice_github main.cpp -o cpp14.out

p6_1:
	g++ -std=c++14 -Wall -Werror -I/home/atul/cpp_practice_github 6.1_dutch_natianal_flag.cpp -o 6_1.out

p6_2:
	g++ -std=c++14 -Wall -Werror -I/home/atul/cpp_practice_github 6.2_plus_one_array.cpp -o 6_2.out

p6_4:
	g++ -std=c++14 -g -Wall -Werror -I/home/atul/cpp_practice_github 6.4_advancing_through_array.cpp -o 6_4.out

p6_5:
	g++ -std=c++14 -Wall -Werror -I/home/atul/cpp_practice_github 6.5_remove_duplicates_from_sorted.cpp -o 6_5.out

p6_8:
	g++ -std=c++14 -Wall -Werror -g -I/home/atul/cpp_practice_github 6.8_prime_generator.cpp -o 6_8.out


